Repository dmk-group/env-dairyforge-devtest, pull requests merged in 2019-08, with the labels that each got.

#1 dspl-frontend-app to 0.0.17
  env/Chart.yaml
  env/requirements.yaml
Labels: size/S

#2 dspl-frontend-app to 0.0.19
  env/requirements.yaml
Labels: size/XS

#3 dspl-frontend-app to 0.0.20
  env/requirements.yaml
Labels: size/XS

#5 pyqs to 0.0.10
  env/requirements.yaml
Labels: size/XS

#6 py-envtest to 0.0.1
  env/requirements.yaml
Labels: size/XS

#7 py-envtest to 0.0.2
  env/requirements.yaml
Labels: size/XS

#9 Fix helm lint
  env/values.yaml
Labels: size/M

#10 Delete application pyqs from this environment
  env/requirements.yaml
Labels: size/XS

#11 py-envtest to 0.0.3
  env/requirements.yaml
Labels: size/XS

#12 py-envtest to 0.0.5
  env/requirements.yaml
Labels: size/XS

#13 py-envtest to 0.0.2
  env/requirements.yaml
Labels: size/XS

#14 py-envtest to 0.0.3
  env/requirements.yaml
Labels: size/XS

#15 Delete application dspl-frontend-app from this environment
  env/requirements.yaml
Labels: size/XS

#16 interchange-app to 1.0.7
  env/requirements.yaml
Labels: size/XS

#17 interchange-app to 1.0.9
  env/requirements.yaml
Labels: size/XS

#18 interchange-app to 1.0.11
  env/requirements.yaml
Labels: size/XS

#19 interchange-app to 1.0.13
  env/requirements.yaml
Labels: size/XS

#20 dspl-frontend-app to 0.0.28
  env/requirements.yaml
Labels: size/XS

#21 dspl-frontend-app to 0.0.30
  env/requirements.yaml
Labels: size/XS

#23 interchange-app to 1.0.17
  env/requirements.yaml
Labels: size/XS

#24 interchange-app to 1.0.19
  env/requirements.yaml
Labels: size/XS

#25 dspl-frontend-app to 0.0.32
  env/requirements.yaml
Labels: size/XS

#26 interchange-app to 1.0.20
  env/requirements.yaml
Labels: size/XS

#27 interchange-app to 1.0.22
  env/requirements.yaml
Labels: size/XS
